// Generated by Flexc++ V2.05.00 on Fri, 11 Aug 2017 14:04:23 +0100

// $insert class_h
#include <sstream>
#include <string.h>
#include <zapata/http/HTTPLexer.h>
#include <zapata/http/HTTPObj.h>
#include <zapata/text/convert.h>

// $insert namespace-use
// UN-comment the next using-declaration if you want to use
// symbols from the namespace zpt without prefixing zpt::
// using namespace zpt;
