// Generated by Bisonc++ V4.04.01 on Sat, 22 Mar 2014 14:40:39 +0000

    // Include this file in the sources of the class JSONTokenizer.

// $insert class.h
#include "JSONTokenizer.h"

// $insert namespace-open
namespace zapata
{

inline void JSONTokenizer::error(char const *msg)
{
    std::cerr << msg << '\n';
}

// $insert lex
inline int JSONTokenizer::lex()
{
    return d_scanner.lex();
}

inline void JSONTokenizer::print()         
{
    print__();           // displays tokens if --print was specified
}

inline void JSONTokenizer::exceptionHandler__(std::exception const &exc)         
{
    throw;              // re-implement to handle exceptions thrown by actions
}

// $insert namespace-close
}

    // Add here includes that are only required for the compilation 
    // of JSONTokenizer's sources.


// $insert namespace-use
    // UN-comment the next using-declaration if you want to use
    // symbols from the namespace zapata without specifying zapata::
//using namespace zapata;

    // UN-comment the next using-declaration if you want to use
    // int JSONTokenizer's sources symbols from the namespace std without
    // specifying std::

//using namespace std;
