// Generated by Flexc++ V1.05.00 on Fri, 21 Mar 2014 16:37:56 +0000

// $insert class_h
#include "JSONLexer.h"

// $insert namespace-use
    // UN-comment the next using-declaration if you want to use
    // symbols from the namespace zapata without prefixing zapata::
//using namespace zapata;
