// Generated by Bisonc++ V4.04.01 on Sun, 23 Mar 2014 13:54:15 +0000

    // Include this file in the sources of the class HTTPTokenizer.

// $insert class.h
#include "HTTPTokenizer.h"

// $insert namespace-open
namespace zapata
{

inline void HTTPTokenizer::error(char const *msg)
{
    std::cerr << msg << '\n';
}

// $insert lex
inline int HTTPTokenizer::lex()
{
    return d_scanner.lex();
}

inline void HTTPTokenizer::print()         
{
    print__();           // displays tokens if --print was specified
}

inline void HTTPTokenizer::exceptionHandler__(std::exception const &exc)         
{
    throw;              // re-implement to handle exceptions thrown by actions
}

// $insert namespace-close
}

    // Add here includes that are only required for the compilation 
    // of HTTPTokenizer's sources.


// $insert namespace-use
    // UN-comment the next using-declaration if you want to use
    // symbols from the namespace zapata without specifying zapata::
//using namespace zapata;

    // UN-comment the next using-declaration if you want to use
    // int HTTPTokenizer's sources symbols from the namespace std without
    // specifying std::

//using namespace std;
