// Generated by Flexc++ V1.05.00 on Tue, 25 Mar 2014 23:01:33 +0000

// $insert class_h
#include "HTTPLexer.h"
#include <string.h>
#include <text/convert.h>
#include <http/HTTPObj.h>

// $insert namespace-use
    // UN-comment the next using-declaration if you want to use
    // symbols from the namespace zapata without prefixing zapata::
//using namespace zapata;
namespace zapata {
	HTTPContentType __HTTP_LEXER_CONTENT_TYPE;
	size_t __HTTP_LEXER_CONTENT_LENGTH;
}
