/*
    Author: Pedro (n@zgul) Figueiredo <pedro.figueiredo@gmail.com>
    Copyright (c) 2014 Pedro (n@zgul)Figueiredo
    This file is part of Zapata.

    Zapata is free software: you can redistribute it and/or modify
    it under the terms of the Lesser GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Zapata is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the Lesser GNU General Public License
    along with Zapata.  If not, see <http://www.gnu.org/licenses/>.
*/

// Generated by Flexc++ V1.05.00 on Tue, 25 Mar 2014 23:01:33 +0000
#pragma once

// $insert class_h
#include "HTTPLexer.h"
#include <string.h>
#include <text/convert.h>
#include <http/HTTPObj.h>

// $insert namespace-use
    // UN-comment the next using-declaration if you want to use
    // symbols from the namespace zapata without prefixing zapata::
//using namespace zapata;
namespace zapata {
}

/*
 	 size_t              d_content_length;
*/
