var annotated =
[
    [ "zapata", null, [
      [ "smart_counter", "classzapata_1_1smart__counter.html", "classzapata_1_1smart__counter" ],
      [ "smart_ref_table", "classzapata_1_1smart__ref__table.html", "classzapata_1_1smart__ref__table" ],
      [ "smart_ptr", "classzapata_1_1smart__ptr.html", "classzapata_1_1smart__ptr" ],
      [ "duo", "classzapata_1_1duo.html", "classzapata_1_1duo" ],
      [ "str_map", "classzapata_1_1str__map.html", "classzapata_1_1str__map" ],
      [ "AssertionException", "classzapata_1_1_assertion_exception.html", "classzapata_1_1_assertion_exception" ],
      [ "CastException", "classzapata_1_1_cast_exception.html", "classzapata_1_1_cast_exception" ],
      [ "InterruptedException", "classzapata_1_1_interrupted_exception.html", "classzapata_1_1_interrupted_exception" ],
      [ "NoAttributeNameException", "classzapata_1_1_no_attribute_name_exception.html", "classzapata_1_1_no_attribute_name_exception" ],
      [ "ParserEOF", "classzapata_1_1_parser_e_o_f.html", "classzapata_1_1_parser_e_o_f" ],
      [ "SyntaxErrorException", "classzapata_1_1_syntax_error_exception.html", "classzapata_1_1_syntax_error_exception" ],
      [ "JSONElement", "classzapata_1_1_j_s_o_n_element.html", "classzapata_1_1_j_s_o_n_element" ],
      [ "JSONBoolRef", "classzapata_1_1_j_s_o_n_bool_ref.html", "classzapata_1_1_j_s_o_n_bool_ref" ],
      [ "JSONIntRef", "classzapata_1_1_j_s_o_n_int_ref.html", "classzapata_1_1_j_s_o_n_int_ref" ],
      [ "JSONDblRef", "classzapata_1_1_j_s_o_n_dbl_ref.html", "classzapata_1_1_j_s_o_n_dbl_ref" ],
      [ "JSONStrRef", "classzapata_1_1_j_s_o_n_str_ref.html", "classzapata_1_1_j_s_o_n_str_ref" ],
      [ "JSONArrRef", "classzapata_1_1_j_s_o_n_arr_ref.html", "classzapata_1_1_j_s_o_n_arr_ref" ],
      [ "JSONObjRef", "classzapata_1_1_j_s_o_n_obj_ref.html", "classzapata_1_1_j_s_o_n_obj_ref" ],
      [ "is_pointer", "structzapata_1_1is__pointer.html", null ],
      [ "is_pointer< T * >", "structzapata_1_1is__pointer_3_01_t_01_5_01_4.html", null ],
      [ "JSONLexer", "classzapata_1_1_j_s_o_n_lexer.html", "classzapata_1_1_j_s_o_n_lexer" ],
      [ "JSONLexerBase", "classzapata_1_1_j_s_o_n_lexer_base.html", "classzapata_1_1_j_s_o_n_lexer_base" ],
      [ "JSONParser", "classzapata_1_1_j_s_o_n_parser.html", "classzapata_1_1_j_s_o_n_parser" ],
      [ "JSONTokenizer", "classzapata_1_1_j_s_o_n_tokenizer.html", "classzapata_1_1_j_s_o_n_tokenizer" ],
      [ "JSONTokenizerBase", "classzapata_1_1_j_s_o_n_tokenizer_base.html", "classzapata_1_1_j_s_o_n_tokenizer_base" ],
      [ "JSONTokenizerLexer", "classzapata_1_1_j_s_o_n_tokenizer_lexer.html", "classzapata_1_1_j_s_o_n_tokenizer_lexer" ],
      [ "Job", "classzapata_1_1_job.html", "classzapata_1_1_job" ],
      [ "JobServer", "classzapata_1_1_job_server.html", "classzapata_1_1_job_server" ],
      [ "NoHeaderNameException", "classzapata_1_1_no_header_name_exception.html", "classzapata_1_1_no_header_name_exception" ],
      [ "HTTPElement", "classzapata_1_1_h_t_t_p_element.html", "classzapata_1_1_h_t_t_p_element" ],
      [ "HTTPReqRef", "classzapata_1_1_h_t_t_p_req_ref.html", "classzapata_1_1_h_t_t_p_req_ref" ],
      [ "HTTPRepRef", "classzapata_1_1_h_t_t_p_rep_ref.html", "classzapata_1_1_h_t_t_p_rep_ref" ],
      [ "HTTPLexer", "classzapata_1_1_h_t_t_p_lexer.html", "classzapata_1_1_h_t_t_p_lexer" ],
      [ "HTTPLexerBase", "classzapata_1_1_h_t_t_p_lexer_base.html", "classzapata_1_1_h_t_t_p_lexer_base" ],
      [ "HTTPParser", "classzapata_1_1_h_t_t_p_parser.html", "classzapata_1_1_h_t_t_p_parser" ],
      [ "HTTPTokenizer", "classzapata_1_1_h_t_t_p_tokenizer.html", "classzapata_1_1_h_t_t_p_tokenizer" ],
      [ "HTTPTokenizerBase", "classzapata_1_1_h_t_t_p_tokenizer_base.html", "classzapata_1_1_h_t_t_p_tokenizer_base" ],
      [ "HTTPTokenizerLexer", "classzapata_1_1_h_t_t_p_tokenizer_lexer.html", "classzapata_1_1_h_t_t_p_tokenizer_lexer" ],
      [ "Mapper", "classzapata_1_1_mapper.html", "classzapata_1_1_mapper" ],
      [ "Partitioner", "classzapata_1_1_partitioner.html", "classzapata_1_1_partitioner" ],
      [ "Reducer", "classzapata_1_1_reducer.html", "classzapata_1_1_reducer" ],
      [ "ClosedException", "classzapata_1_1_closed_exception.html", "classzapata_1_1_closed_exception" ],
      [ "basic_socketbuf", "classzapata_1_1basic__socketbuf.html", "classzapata_1_1basic__socketbuf" ],
      [ "basic_socketstream", "classzapata_1_1basic__socketstream.html", "classzapata_1_1basic__socketstream" ],
      [ "basic_serversocketstream", "classzapata_1_1basic__serversocketstream.html", "classzapata_1_1basic__serversocketstream" ],
      [ "basic_sslsocketbuf", "classzapata_1_1basic__sslsocketbuf.html", "classzapata_1_1basic__sslsocketbuf" ],
      [ "basic_sslsocketstream", "classzapata_1_1basic__sslsocketstream.html", "classzapata_1_1basic__sslsocketstream" ],
      [ "basic_serversslsocketstream", "classzapata_1_1basic__serversslsocketstream.html", "classzapata_1_1basic__serversslsocketstream" ],
      [ "RESTPool", "classzapata_1_1_r_e_s_t_pool.html", "classzapata_1_1_r_e_s_t_pool" ],
      [ "FileRemove", "classzapata_1_1_file_remove.html", "classzapata_1_1_file_remove" ],
      [ "FileUpload", "classzapata_1_1_file_upload.html", "classzapata_1_1_file_upload" ],
      [ "RESTCollection", "classzapata_1_1_r_e_s_t_collection.html", "classzapata_1_1_r_e_s_t_collection" ],
      [ "RESTController", "classzapata_1_1_r_e_s_t_controller.html", "classzapata_1_1_r_e_s_t_controller" ],
      [ "RESTDocument", "classzapata_1_1_r_e_s_t_document.html", "classzapata_1_1_r_e_s_t_document" ],
      [ "RESTResource", "classzapata_1_1_r_e_s_t_resource.html", "classzapata_1_1_r_e_s_t_resource" ],
      [ "RESTStore", "classzapata_1_1_r_e_s_t_store.html", "classzapata_1_1_r_e_s_t_store" ],
      [ "RESTJob", "classzapata_1_1_r_e_s_t_job.html", "classzapata_1_1_r_e_s_t_job" ],
      [ "RESTServer", "classzapata_1_1_r_e_s_t_server.html", "classzapata_1_1_r_e_s_t_server" ]
    ] ]
];