#!/bin/bash

distro=$(lsb_release -cs)
name=$1
abbreviation=$2
dev_email=$3
dev_name=$4
path_prefix=$5
underscore_name=$(echo $1 | sed -r 's#-#_#g')
underscore_abbr=$(echo $2 | sed -r 's#-#_#g')
upper_name=$(echo $underscore_name | awk '{print toupper($0)}')
upper_abbr=$(echo $abbreviation | awk '{print toupper($0)}')

special_files=(.gitignore .zpt_rc configure.ac)

for special_file in ${special_files[@]}
do
    sed -i "s#project-name#$name#g" $special_file
    sed -i "s#project_name#$underscore_name#g" $special_file
    sed -i "s#PROJECT_NAME#$upper_name#g" $special_file
    sed -i "s#project-abbreviation#$path_prefix/$abbreviation#g" $special_file
    sed -i "s#project_abbreviation#$path_prefix/$underscore_abbr#g" $special_file
    sed -i "s#PROJECT_ABBREVIATION#$path_prefix/$upper_abbr#g" $special_file
    sed -i "s#developer-name#$dev_name#g" $special_file
    sed -i "s#developer-email#$dev_email#g" $special_file
    sed -i "s#distro-version#$distro#g" $special_file
done

files=$(find . -name "*")
for file in ${files[@]}
do
	if [ -f $file ]
	then
		sed -i "s#project-name#$name#g" $file
		sed -i "s#project_name#$underscore_name#g" $file
		sed -i "s#PROJECT_NAME#$upper_name#g" $file
		sed -i "s#/project-abbreviation/#/$path_prefix/$abbreviation/#g" $file
		sed -i "s#/project_abbreviation/#/$path_prefix/$underscore_abbr/#g" $file
		sed -i "s#/PROJECT_ABBREVIATION/#/$path_prefix/$upper_abbr/#g" $file
		sed -i "s#project-abbreviation#$abbreviation#g" $file
		sed -i "s#project_abbreviation#$underscore_abbr#g" $file
		sed -i "s#PROJECT_ABBREVIATION#$upper_abbr#g" $file
		sed -i "s#developer-name#$dev_name#g" $file
		sed -i "s#developer-email#$dev_email#g" $file
		sed -i "s#distro-version#$distro#g" $file
	fi
done

name_dirs=$(find . -name "project-name*")
for file in ${name_dirs[@]}
do
	if [ -d $file ]
	then
		fullname=${file#*./}
		prefix=${fullname%/*}
		mkdir -p "$prefix/$path_prefix"
		mv $file "$prefix/$path_prefix/$name"
	fi
done

abbr_dirs=$(find . -name "project-abbreviation*")
for file in ${abbr_dirs[@]}
do
	if [ -d $file ]
	then
		fullname=${file#*./}
		prefix=${fullname%/*}
		mkdir -p "$prefix/$path_prefix"
		mv $file "$prefix/$path_prefix/$abbreviation"
	fi
done

name_files=$(find . -name "project-name*")
for file in ${name_files[@]}
do
	if [ -f $file ]
	then
		fullname=${file#*./}
		prefix=${fullname%/*}
		filename=${fullname##*/}
		suffix=${filename##*.}
		if [[ $suffix == "project-name" ]]
		then
			mv $file "$prefix/$name"
		else 
			mv $file "$prefix/$name.$suffix"
		fi
	fi
done

abbr_files=$(find . -name "project-abbreviation*")
for file in ${abbr_files[@]}
do
	if [ -f $file ]
	then
		fullname=${file#*./}
		prefix=${fullname%/*}
		filename=${fullname##*/}
		suffix=${filename#*.}
		if [[ $suffix == "project-abbreviation" ]]
		then
			mv $file "$prefix/$abbreviation"
		else 
		    mkdir -p "$prefix/$path_prefix"
		    mv $file "$prefix/$path_prefix/$name.$suffix"
		    # mv $file "$prefix/$abbreviation.$suffix"
		fi
	fi
done
