#!/bin/bash

distro=$(lsb_release -cs)
fullbranch=$(git rev-parse --abbrev-ref HEAD)
environment=${fullbranch##*/}
name=$1
abbreviation=$2
dev_email=$3
dev_name=$4
path_prefix="$5/"
underscore_name=$(echo $1 | sed -r 's#-#_#g')
underscore_abbr=$(echo $2 | sed -r 's#-#_#g')
upper_name=$(echo $underscore_name | awk '{print toupper($0)}')
upper_abbr=$(echo $abbreviation | awk '{print toupper($0)}')

special_files=(configure.ac debian/changelog)

for file in ${special_files[@]}
do
    sed -i "s#project-name#$name#g" $file
    sed -i "s#project_name#$underscore_name#g" $file
    sed -i "s#PROJECT_NAME#$upper_name#g" $file
    sed -i "s#/project-abbreviation/#/$path_prefix/$abbreviation/#g" $file
    sed -i "s#/project_abbreviation/#/$path_prefix/$underscore_abbr/#g" $file
    sed -i "s#/PROJECT_ABBREVIATION/#/$path_prefix/$upper_abbr/#g" $file
    sed -i "s#project-abbreviation#$abbreviation#g" $file
    sed -i "s#project_abbreviation#$underscore_abbr#g" $file
    sed -i "s#PROJECT_ABBREVIATION#$upper_abbr#g" $file
    sed -i "s#developer-name#$dev_name#g" $file
    sed -i "s#developer-email#$dev_email#g" $file
    sed -i "s#distro-version#$distro#g" $file
    sed -i "s#environment#$environment#g" $file
    sed -i "s#project-prefix#$path_prefix#g" $file
done
