#! /bin/bash

### BEGIN INIT INFO
# Provides:          zapata
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: RESTful API's C++ toolkit named after Emiliano Zapata - RESTful server daemon
# Description:       Provides a set of C++ tool libraries for the development of RESTful API's. This script loads every service container described in '/etc/zapata/backend-enabled/'
### END INIT INFO

cwd=${BASH_SOURCE%/*}
prefix=${cwd%%/etc/init.d}

if [ -z $prefix ]
then
	bin_dir=/usr/bin
else 
	bin_dir=$prefix/bin
fi
daemon=$bin_dir/zpt
cnf_file=/etc/zapata/zapata.conf
run_dir=/var/run
name="zapata"

start_zapata() {
    cur_pid_file="$run_dir/zapata.pid"
    if [ -f $cur_pid_file ]
    then
	cur_pid=$(<"$cur_pid_file")
	pid_run=$(ps -p $cur_pid | grep $cur_pid | awk '{ print $1 }')
	if [ -z $pid_run ]
	then
	    rm -rf $cur_pid_file
	else
	    log_daemon_msg "zapata already running, stop before start"
	    exit -1
	fi
    fi

    [ -f /etc/default/zapata.rc ] && source /etc/default/zapata.rc
    start-stop-daemon --start -b --oknodo --quiet --make-pidfile --pidfile $cur_pid_file --startas $daemon -- -c $cnf_file &> /dev/null
}

stop_zapata() {
    cur_pid_file="$run_dir/zapata.pid"
    start-stop-daemon --stop --oknodo --quiet --remove-pidfile --pidfile $cur_pid_file &> /dev/null
}

case "$1" in
    start)
	start_zapata "starting"
	;;
    stop)
	stop_zapata "stopping"
	;;
    restart)
	stop_zapata "restarting"
	start_zapata "restarting"
	;;
esac
