#!/bin/bash

apt-get -y update
apt-get -yy upgrade
apt-get -yy dist-upgrade

pushd /root/zapata

git pull
sed -i 's#yakkety#xenial#g' $(grep -l -R yakkety *)
make config && make && make distcheck && make deb
cp $(find . -name *.deb) /var/cache/zapata

popd
