// Generated by Flexc++ V2.07.07 on Sat, 16 May 2020 16:56:43 -44156756

// $insert class_h
#include <zapata/json/JSONLexer.h>

// $insert namespace-use
// UN-comment the next using-declaration if you want to use
// symbols from the namespace zpt without prefixing zpt::
// using namespace zpt;
