// Generated by Flexc++ V2.07.03 on Mon, 11 Nov 2019 00:26:15 +0000

// $insert class_h
#include <zapata/json/JSONLexer.h>

// $insert namespace-use
// UN-comment the next using-declaration if you want to use
// symbols from the namespace zpt without prefixing zpt::
// using namespace zpt;
