// Generated by Flexc++ V2.03.04 on Sat, 21 May 2016 01:29:51 +0100

// $insert class_h
#include "JSONLexer.h"

// $insert namespace-use
    // UN-comment the next using-declaration if you want to use
    // symbols from the namespace zpt without prefixing zpt::
//using namespace zpt;
