
package: core http map_reduce map_reduce_cluster mongodb net rest rest_server users

core:
	make package -C zapata-core

http:
	make package -C zapata-http

map_reduce:
	make package -C zapata-map-reduce

map_reduce_cluster:
	make package -C zapata-map-reduce-cluster

mongodb:
	make package -C zapata-mongodb

net:
	make package -C zapata-net

rest:
	make package -C zapata-rest

users:
	make package -C zapata-users

rest_server:
	make package -C zapata-rest-server
