// Generated by Flexc++ V2.07.03 on Sat, 04 Apr 2020 13:21:20 +0100

// $insert class_h
#include "URILexer.h"

// $insert namespace-use
// UN-comment the next using-declaration if you want to use
// symbols from the namespace zpt without prefixing zpt::
// using namespace zpt;
namespace zpt {
namespace uri {
namespace lex {
enum Tokens_ { DOUBLE_DOT = 257, SLASH, AT, QMARK, EQ, E, STRING, FUNCTION_PARAM };
}
}
}
