// Generated by Flexc++ V2.07.03 on Sun, 03 Nov 2019 23:40:20 +0000

// $insert class_h
#include <zapata/events/URILexer.h>

// $insert namespace-use
// UN-comment the next using-declaration if you want to use
// symbols from the namespace zpt without prefixing zpt::
// using namespace zpt;
