// Generated by Flexc++ V2.07.07 on Sun, 17 May 2020 23:54:29 -44159854

// $insert class_h
#include "URILexer.h"

// $insert namespace-use
// UN-comment the next using-declaration if you want to use
// symbols from the namespace zpt without prefixing zpt::
// using namespace zpt;
namespace zpt {
namespace uri {
namespace lex {
enum Tokens_ { DOUBLE_DOT = 257, SLASH, AT, QMARK, EQ, E, STRING, FUNCTION_PARAM, CARDINAL };
}
}
}
