// Generated by Bisonc++ V6.02.05 on Sun, 24 Nov 2019 21:03:50 +0000

    // Include this file in the sources of the class URITokenizer.

// $insert class.h
#include "URITokenizer.h"

// $insert namespace-open
namespace zpt
{

inline void URITokenizer::error()
{
    std::cerr << "Syntax error\n";
}

// $insert lex
inline int URITokenizer::lex()
{
    return d_scanner.lex();
}

inline void URITokenizer::print()         
{
}

inline void URITokenizer::exceptionHandler(std::exception const &exc)         
{
    throw;              // re-implement to handle exceptions thrown by actions
}

// $insert namespace-close
}

    // Add here includes that are only required for the compilation 
    // of URITokenizer's sources.


// $insert namespace-use
    // UN-comment the next using-declaration if you want to use
    // symbols from the namespace zpt without specifying zpt::
//using namespace zpt;

    // UN-comment the next using-declaration if you want to use
    // int URITokenizer's sources symbols from the namespace std without
    // specifying std::

//using namespace std;
