#!/bin/bash

if [[ "$1" == "" ]]
then
	echo "must specify an Ubuntu flavour"
	exit -1
fi

flavour=$1

docker run --rm -i -t -v /var/cache/zapata/${flavour}:/var/cache/zapata naazgull/zapata:build-${flavour}
