#!/bin/bash

mkdir -p upstream
rm -rf upstream/*
rm -rf *.deb
for f in *.tar.gz
do
    fullname=${f%.tar.gz}
    prefix=${fullname##*/}
    revision=${prefix##*-}
    no_revision_prefix=${prefix%-*}
    version=${no_revision_prefix##*-}
    no_version_prefix=${no_revision_prefix%-*}
    orig=upstream/$no_version_prefix\_$version.orig.tar.gz
    echo "processing $orig"
    cp -rf $f $orig
    pushd upstream/
    tar xvzf $no_version_prefix\_$version.orig.tar.gz
    pushd $prefix/
    debuild -us -uc
    if [[ $? != 0 ]]
    then
	exit -1
    fi
    sudo mv ../*.deb ../../
    if [[ $? != 0 ]]
    then
	exit -1
    fi
    popd
    popd
done
rm -rfv upstream/
