// Generated by Flexc++ V2.08.01 on Sun, 13 Feb 2022 15:53:59 +0000

#ifndef zptFunctionalLexer_H_INCLUDED_
#define zptFunctionalLexer_H_INCLUDED_

// $insert baseclass_h
#include "FunctionalLexerbase.h"

// $insert namespace-open
namespace zpt {

// $insert classHead
class FunctionalLexer : public FunctionalLexerBase {
  public:
    explicit FunctionalLexer(std::istream& in = std::cin, std::ostream& out = std::cout);

    FunctionalLexer(std::string const& infile, std::string const& outfile);

    // $insert lexFunctionDecl
    int lex();

  private:
    int lex_();
    int executeAction_(size_t ruleNr);

    void print();
    void preCode(); // re-implement this function for code that must
                    // be exec'ed before the patternmatching starts

    void postCode(PostEnum_ type);
    // re-implement this function for code that must
    // be exec'ed after the rules's actions.
};

// $insert scannerConstructors
inline FunctionalLexer::FunctionalLexer(std::istream& in, std::ostream& out)
  : FunctionalLexerBase(in, out) {}

inline FunctionalLexer::FunctionalLexer(std::string const& infile, std::string const& outfile)
  : FunctionalLexerBase(infile, outfile) {}

// $insert inlineLexFunction
inline int
FunctionalLexer::lex() {
    return lex_();
}

inline void
FunctionalLexer::preCode() {
    // optionally replace by your own code
}

inline void
FunctionalLexer::postCode([[maybe_unused]] PostEnum_ type) {
    // optionally replace by your own code
}

inline void
FunctionalLexer::print() {
    print_();
}

// $insert namespace-close
}

#endif // FunctionalLexer_H_INCLUDED_
