// Generated by Flexc++ V2.08.01 on Sun, 13 Feb 2022 13:55:49 +0000

// $insert class_h
#include "FunctionalLexer.h"

// $insert namespace-use
// UN-comment the next using-declaration if you want to use
// symbols from the namespace zpt without prefixing zpt::
// using namespace zpt;
namespace zpt {
namespace functional {
namespace lex {
enum Tokens_ {
    TOKEN = 257,
    LPAREN,
    RPAREN,
    COMMA,
};
}
}
}
