// Generated by Flexc++ V2.11.00 on Tue, 03 May 2022 16:22:23 +0100

// $insert class_h
#include "FunctionalLexer.h"

// $insert namespace-use
// UN-comment the next using-declaration if you want to use
// symbols from the namespace zpt without prefixing zpt::
// using namespace zpt;
namespace zpt {
namespace functional {
namespace lex {
enum Tokens_ {
    STRING = 257,
    NUMBER,
    VARIABLE,
    LPAREN,
    RPAREN,
    COMMA,
};
}
}
}
