/* Generated by re2c 4.6 on Tue Sep 29 11:46:01 2026 */
#line 1 "parsers/functional/src/Functional.re"
/*
  This is free and unencumbered software released into the public domain.

  Anyone is free to copy, modify, publish, use, compile, sell, or distribute
  this software, either in source code form or as a compiled binary, for any
  purpose, commercial or non-commercial, and by any means.

  In jurisdictions that recognize copyright laws, the author or authors of this
  software dedicate any and all copyright interest in the software to the public
  domain. We make this dedication for the benefit of the public at large and to
  the detriment of our heirs and successors. We intend this dedication to be an
  overt act of relinquishment in perpetuity of all present and future rights to
  this software under copyright law.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
  AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
  ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
  WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

/*
 * re2c lexer for functional-style expressions (e.g. `gt(integer(0,2),float(1,2,3))`).
 * Ported from the original flexc++ lexer in Functional.f. Each start
 * condition becomes one ordinary (non-`--conditions`) re2c block compiled
 * into one Re2cFunctionalLexer method; YYCURSOR/YYLIMIT/YYMARKER map onto
 * the buffer pointers owned by Re2cFunctionalLexer, and YYFILL maps onto
 * Re2cFunctionalLexer::yyfill().
 *
 * captureMatch() is called as the first statement of every rule action that
 * either returns a token or participates in a more()-chain, mirroring
 * flexc++'s matched_(). Any more() call in an action must come AFTER
 * captureMatch(), since more() affects how the *next* rule's match combines
 * with what was just captured here, not this one. Rules that neither return
 * a token nor build towards a later more()-chain (plain whitespace) skip
 * captureMatch() entirely, matching flexc++'s empty-bodied whitespace rule.
 *
 * Number accumulation chains exactly as in Functional.f: INITIAL's `[0-9]`
 * rule captures the first digit, arms more(), and switches to `number`;
 * `number`'s `[0-9.]*` rule (which may legitimately match zero characters)
 * then appends the rest and returns NUMBER. lexNumber() intentionally has
 * no catch-all `* {}` rule - adding one would let re2c's longest-match
 * policy prefer consuming one stray byte (length 1) over the legitimate
 * zero-length match of `[0-9.]*`, corrupting whatever follows the number.
 * Since `[0-9.]*` already matches every possible input (including zero
 * characters), no catch-all is needed or safe here.
 *
 * Every greedy `[^...]+` exclusion class excludes `\x00`, for the same
 * reason established in URI.re: yyfill() zero-pads the buffer with
 * synthetic NUL bytes once the underlying stream is exhausted, and this
 * grammar (like URI, unlike JSON/HTTP) has no explicit "value complete"
 * signal short of real stream EOF.
 */

#include <sstream>
#include <zapata/functional/Re2cFunctionalLexer.h>
#include <zapata/functional/FunctionalParser.bison.h>

namespace {
#line 68 "parsers/functional/src/Functional.re"

} // namespace

auto zpt::Re2cFunctionalLexer::lexInitial() -> int {
    
#line 70 "parsers/functional/src/FunctionalLexer.re2c.cpp"
{
	char yych;
	if (this->__limit <= this->__cursor) this->yyfill(1);
	yych = *this->__cursor;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ': goto yy4;
		case '"': goto yy5;
		case '(': goto yy6;
		case ')': goto yy7;
		case ',': goto yy8;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy9;
		default: goto yy2;
	}
yy1:
	++this->__cursor;
#line 102 "parsers/functional/src/Functional.re"
	{ return 0; }
#line 102 "parsers/functional/src/FunctionalLexer.re2c.cpp"
yy2:
	++this->__cursor;
	if (this->__limit <= this->__cursor) this->yyfill(1);
	yych = *this->__cursor;
	switch (yych) {
		case 0x00:
		case '\t':
		case '\n':
		case '\f':
		case '\r':
		case ' ':
		case '"':
		case '(':
		case ')':
		case ',':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy3;
		default: goto yy2;
	}
yy3:
#line 79 "parsers/functional/src/Functional.re"
	{
            this->captureMatch();
            return VARIABLE;
        }
#line 136 "parsers/functional/src/FunctionalLexer.re2c.cpp"
yy4:
	++this->__cursor;
#line 99 "parsers/functional/src/Functional.re"
	{
            return 0;
        }
#line 143 "parsers/functional/src/FunctionalLexer.re2c.cpp"
yy5:
	++this->__cursor;
#line 95 "parsers/functional/src/Functional.re"
	{
            this->begin(re2c_functional_cond::quoted);
            return 0;
        }
#line 151 "parsers/functional/src/FunctionalLexer.re2c.cpp"
yy6:
	++this->__cursor;
#line 83 "parsers/functional/src/Functional.re"
	{
            this->captureMatch();
            return LPAREN;
        }
#line 159 "parsers/functional/src/FunctionalLexer.re2c.cpp"
yy7:
	++this->__cursor;
#line 87 "parsers/functional/src/Functional.re"
	{
            this->captureMatch();
            return RPAREN;
        }
#line 167 "parsers/functional/src/FunctionalLexer.re2c.cpp"
yy8:
	++this->__cursor;
#line 91 "parsers/functional/src/Functional.re"
	{
            this->captureMatch();
            return COMMA;
        }
#line 175 "parsers/functional/src/FunctionalLexer.re2c.cpp"
yy9:
	++this->__cursor;
#line 73 "parsers/functional/src/Functional.re"
	{
            this->captureMatch();
            this->more();
            this->begin(re2c_functional_cond::number);
            return 0;
        }
#line 185 "parsers/functional/src/FunctionalLexer.re2c.cpp"
}
#line 103 "parsers/functional/src/Functional.re"

}

auto zpt::Re2cFunctionalLexer::lexQuoted() -> int {
    
#line 193 "parsers/functional/src/FunctionalLexer.re2c.cpp"
{
	char yych;
	if (this->__limit <= this->__cursor) this->yyfill(1);
	yych = *this->__cursor;
	switch (yych) {
		case 0x00: goto yy11;
		case '"': goto yy14;
		default: goto yy12;
	}
yy11:
	++this->__cursor;
#line 120 "parsers/functional/src/Functional.re"
	{ return 0; }
#line 207 "parsers/functional/src/FunctionalLexer.re2c.cpp"
yy12:
	++this->__cursor;
	if (this->__limit <= this->__cursor) this->yyfill(1);
	yych = *this->__cursor;
	switch (yych) {
		case 0x00:
		case '"': goto yy13;
		default: goto yy12;
	}
yy13:
#line 115 "parsers/functional/src/Functional.re"
	{
            this->captureMatch();
            this->more();
            return 0;
        }
#line 224 "parsers/functional/src/FunctionalLexer.re2c.cpp"
yy14:
	++this->__cursor;
#line 108 "parsers/functional/src/Functional.re"
	{
            this->captureMatch();
            std::string _content(this->matched());
            this->setMatched(_content.substr(0, _content.length() - 1));
            this->begin(re2c_functional_cond::INITIAL);
            return STRING;
        }
#line 235 "parsers/functional/src/FunctionalLexer.re2c.cpp"
}
#line 121 "parsers/functional/src/Functional.re"

}

auto zpt::Re2cFunctionalLexer::lexNumber() -> int {
    
#line 243 "parsers/functional/src/FunctionalLexer.re2c.cpp"
{
	char yych;
	goto yy15;
yy16:
	++this->__cursor;
yy15:
	if (this->__limit <= this->__cursor) this->yyfill(1);
	yych = *this->__cursor;
	switch (yych) {
		case '.':
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy16;
		default: goto yy17;
	}
yy17:
#line 126 "parsers/functional/src/Functional.re"
	{
            this->captureMatch();
            this->begin(re2c_functional_cond::INITIAL);
            return NUMBER;
        }
#line 273 "parsers/functional/src/FunctionalLexer.re2c.cpp"
}
#line 131 "parsers/functional/src/Functional.re"

}
