// Generated by Flexc++ V1.08.00 on Sat, 21 Feb 2015 17:17:31 +0000

// $insert class_h
#include "JSONLexer.h"

// $insert namespace-use
    // UN-comment the next using-declaration if you want to use
    // symbols from the namespace zapata without prefixing zapata::
//using namespace zapata;
