#! /bin/bash

daemon=/usr/bin/zapata-rest-daemon
cnf_dir=/etc/zapata/backend-enabled
run_dir=/var/run

pushd $cnf_dir &> /dev/null
while true
do
	for cnf_file in *.conf
	do
		if [ -f $cnf_file ]
		then
			backend_name=${cnf_file%%.conf}
			cur_pid_file="$run_dir/zapata.$backend_name.pid"
			cnf_file="$cnf_dir/$cnf_file"

			if [ -f $cur_pid_file ]
			then
				cur_pid=$(<"$cur_pid_file")
				pid_run=$(ps -p $cur_pid | grep $cur_pid | awk '{ print $1 }')
				if [ -z $pid_run ]
				then
					rm -rf $cur_pid_file
					echo -n "* restarting '$backend_name': "
					start-stop-daemon --start -b --oknodo --quiet --make-pidfile --pidfile $cur_pid_file --exec $daemon -- -c $cnf_file
					echo "done."
				fi
			fi

		fi
	done

	sleep 10
done
