// Generated by Bisonc++ V6.02.05 on Fri, 08 Nov 2019 02:29:05 +0000

// base/comment

// $insert class.ih
#include "URITokenizerimpl.h"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token is Reserved_::UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN_ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on errTok_
// which is applied. In this errTok_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
//      }

// base/declarations
// $insert debugincludes
#include <iostream>
#include <sstream>
#include <string>
#include <iomanip>
#include <unordered_map>

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum Reserved_
    {
        UNDETERMINED_   = -2,
        EOF_            = -1,
        errTok_         = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    inline bool operator&(StateType lhs, StateType rhs)
    {
        return (static_cast<int>(lhs) & rhs) != 0;
    }
    enum StateTransition
    {
        ACCEPT_   = 0,     // `ACCEPT' TRANSITION
    };

    struct PI_     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR_     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            StateType d_type;
            int       d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION_ = 10
    };

// Productions Info Records:
PI_ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {265, 5}, // 1: exp ->  scheme #0001 path #0002 params
     {268, 0}, // 2: #0001 ->  <empty>
     {270, 0}, // 3: #0002 ->  <empty>
     {266, 0}, // 4: scheme ->  <empty>
     {266, 3}, // 5: scheme (SCHEME) ->  SCHEME DOUBLE_DOT SLASH
     {267, 0}, // 6: path ->  <empty>
     {267, 3}, // 7: path (SLASH) ->  SLASH PATH_PART path
     {269, 0}, // 8: params ->  <empty>
     {269, 2}, // 9: params (QMARK) ->  QMARK paramslist
     {271, 3}, // 10: paramslist (STRING) ->  STRING EQ paramvalue
     {271, 5}, // 11: paramslist (E) ->  paramslist E STRING EQ paramvalue
     {272, 0}, // 12: paramvalue ->  <empty>
     {272, 1}, // 13: paramvalue (STRING) ->  STRING
     {273, 1}, // 14: exp_$ ->  exp
};

// State info and SR_ transitions for each state.


SR_ s_0[] =
{
    { { REQ_DEF}, {  4} },          
    { {     265}, {  1} }, // exp   
    { {     266}, {  2} }, // scheme
    { {     257}, {  3} }, // SCHEME
    { {       0}, { -4} },          
};

SR_ s_1[] =
{
    { { REQ_TOKEN}, {       2} }, 
    { {      EOF_}, { ACCEPT_} }, 
    { {         0}, {       0} }, 
};

SR_ s_2[] =
{
    { { DEF_RED}, {  2} },         
    { {     268}, {  4} }, // #0001
    { {       0}, { -2} },         
};

SR_ s_3[] =
{
    { { REQ_TOKEN}, { 2} },              
    { {       258}, { 5} }, // DOUBLE_DOT
    { {         0}, { 0} },              
};

SR_ s_4[] =
{
    { { REQ_DEF}, {  3} },         
    { {     267}, {  6} }, // path 
    { {     259}, {  7} }, // SLASH
    { {       0}, { -6} },         
};

SR_ s_5[] =
{
    { { REQ_TOKEN}, { 2} },         
    { {       259}, { 8} }, // SLASH
    { {         0}, { 0} },         
};

SR_ s_6[] =
{
    { { DEF_RED}, {  2} },         
    { {     270}, {  9} }, // #0002
    { {       0}, { -3} },         
};

SR_ s_7[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       260}, { 10} }, // PATH_PART
    { {         0}, {  0} },             
};

SR_ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR_ s_9[] =
{
    { { REQ_DEF}, {  3} },          
    { {     269}, { 11} }, // params
    { {     261}, { 12} }, // QMARK 
    { {       0}, { -8} },          
};

SR_ s_10[] =
{
    { { REQ_DEF}, {  3} },         
    { {     267}, { 13} }, // path 
    { {     259}, {  7} }, // SLASH
    { {       0}, { -6} },         
};

SR_ s_11[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR_ s_12[] =
{
    { { REQ_TOKEN}, {  3} },              
    { {       271}, { 14} }, // paramslist
    { {       264}, { 15} }, // STRING    
    { {         0}, {  0} },              
};

SR_ s_13[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR_ s_14[] =
{
    { { REQ_DEF}, {  2} },     
    { {     263}, { 16} }, // E
    { {       0}, { -9} },     
};

SR_ s_15[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       262}, { 17} }, // EQ
    { {         0}, {  0} },      
};

SR_ s_16[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       264}, { 18} }, // STRING
    { {         0}, {  0} },          
};

SR_ s_17[] =
{
    { { REQ_DEF}, {   3} },              
    { {     272}, {  19} }, // paramvalue
    { {     264}, {  20} }, // STRING    
    { {       0}, { -12} },              
};

SR_ s_18[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       262}, { 21} }, // EQ
    { {         0}, {  0} },      
};

SR_ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR_ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR_ s_21[] =
{
    { { REQ_DEF}, {   3} },              
    { {     272}, {  22} }, // paramvalue
    { {     264}, {  20} }, // STRING    
    { {       0}, { -12} },              
};

SR_ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};


// State array:
SR_ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,
};

typedef std::unordered_map<int, char const *> SMap;
typedef SMap::value_type SMapVal;

SMapVal s_symArr[] =
{
    SMapVal(-2, "Reserved_::UNDETERMINED_"),  // predefined symbols
    SMapVal(-1, "Reserved_::EOF_"),
    SMapVal(256, "errTok_"),

    SMapVal(257, "SCHEME"),
    SMapVal(258, "DOUBLE_DOT"),
    SMapVal(259, "SLASH"),
    SMapVal(260, "PATH_PART"),
    SMapVal(261, "QMARK"),
    SMapVal(262, "EQ"),
    SMapVal(263, "E"),
    SMapVal(264, "STRING"),
    SMapVal(265, "exp"),
    SMapVal(266, "scheme"),
    SMapVal(267, "path"),
    SMapVal(268, "#0001"),
    SMapVal(269, "params"),
    SMapVal(270, "#0002"),
    SMapVal(271, "paramslist"),
    SMapVal(272, "paramvalue"),
    SMapVal(273, "exp_$"),
};

SMap s_symbol
(
    s_symArr, s_symArr + sizeof(s_symArr) / sizeof(SMapVal)
);

} // anonymous namespace ends


// $insert namespace-open
namespace zpt
{


// If the parsing function call (i.e., parse()' needs arguments, then provide
// an overloaded function.  The code below doesn't rely on parameters, so no
// arguments are required.  Furthermore, parse uses a function try block to
// allow us to do ACCEPT and ABORT from anywhere, even from within members
// called by actions, simply throwing the appropriate exceptions.


// base/base1
URITokenizerBase::URITokenizerBase()
:
    d_token(Reserved_::UNDETERMINED_),
    // $insert baseclasscode
    d_requiredTokens_(0)
{
}

// base/clearin
void URITokenizerBase::clearin_()
{
    d_nErrors_ = 0;
    d_stackIdx = -1;
    d_stateStack.clear();
    d_token = Reserved_::UNDETERMINED_;
    d_next = TokenPair{ Reserved_::UNDETERMINED_, STYPE_{} };
    d_recovery = false;
    d_acceptedTokens_ = d_requiredTokens_;
    d_val_ = STYPE_{};

    push_(0);
}

// base/debugfunctions
// $insert debugfunctions
std::ostringstream URITokenizerBase::s_out_;
std::ostream &URITokenizerBase::dflush_(std::ostream &out)
{
    std::ostringstream &s_out_ = dynamic_cast<std::ostringstream &>(out);

    std::cout << "    " << s_out_.str() << std::flush;
    s_out_.clear();
    s_out_.str("");
    return out;
}

std::string URITokenizerBase::stype_(char const *pre, 
                 STYPE_ const &semVal, char const *post) const
{
    return "";
}
std::string URITokenizerBase::symbol_(int value) const
{
    using namespace std;
    ostringstream ostr;
    SMap::const_iterator it = s_symbol.find(value);
    if (it != s_symbol.end())
        ostr << '\'' << it->second << '\'';
    else if (isprint(value))
        ostr << '`' << static_cast<char>(value) << "' (" << value << ')';
    else
        ostr << "'\\x" << setfill('0') << hex << setw(2) << value << '\'';
    return ostr.str();
}



void URITokenizerBase::setDebug(bool mode)
{
    d_actionCases_ = false;
    d_debug_ = mode;
}

void URITokenizerBase::setDebug(DebugMode_ mode)
{
    d_actionCases_ = mode & ACTIONCASES;
    d_debug_ =       mode & ON;
}

// base/lex
void URITokenizerBase::lex_(int token)
{
    d_token = token;

    if (d_token <= 0)
        d_token = Reserved_::EOF_;

    d_terminalToken = true;
}

// base/lookup
int URITokenizerBase::lookup_() const
{
    // if the final transition is negative, then we should reduce by the rule
    // given by its positive value.

    SR_ const *sr = s_state[d_state];
    SR_ const *last = sr + sr->d_lastIdx;

    for ( ; ++sr != last; )           // visit all but the last SR entries
    {
        if (sr->d_token == d_token)
            return sr->d_action;
    }

    if (sr == last)   // reached the last element
    {
        if (sr->d_action < 0)   // default reduction
        {
            // $insert debug
            if (d_debug_)
                s_out_ <<  "\nLOOKUP: [" << state_() << ", " << symbol_(d_token) << "] -> default reduce using rule " << -sr->d_action << '\n' << dflush_;
            return sr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN_;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = sr->d_action;

// $insert debuglookup
    if (d_debug_)
    {
        s_out_ <<  "encountered " << symbol_(token_()) << " in state " <<
                    state_() << ": ";
    
        if (action < 0)             // a reduction was found
            s_out_ << ": reducing by rule " << -action;
        else if (action == 0)
            s_out_ <<  "ACCEPT";
        else
            s_out_ <<  "next state: " << action;
    
        s_out_ << '\n' << dflush_;
    }

    return action;
}

// base/pop
void URITokenizerBase::pop_(size_t count)
{
    // $insert debug
    if (d_debug_)
        s_out_ <<  "pop " << count << " elements from the stack having size " << stackSize_() << '\n' << dflush_;
    if (d_stackIdx < static_cast<int>(count))
    {
        // $insert debug
        if (d_debug_)
            s_out_ <<  "Terminating parse(): state stack underflow  at token " << symbol_(d_token) << '\n' << dflush_;
        ABORT();
    }

    d_stackIdx -= count;
    d_state = d_stateStack[d_stackIdx].first;
    d_vsp = &d_stateStack[d_stackIdx];

    // $insert debug
    if (d_debug_)
        s_out_ <<  "next: [" << state_() << ", " << symbol_(d_token) << ']' << stype_(". Semantic: ", vs_(0)) << '\n' << dflush_;
}

// base/poptoken
void URITokenizerBase::popToken_()
{
    d_token = d_next.first;
    d_val_ = std::move(d_next.second);

    d_next.first = Reserved_::UNDETERMINED_;
}

// base/push
void URITokenizerBase::push_(size_t state)
{
    size_t currentSize = d_stateStack.size();
    if (stackSize_() == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION_;
        d_stateStack.resize(newSize);
    }

    ++d_stackIdx;
    d_stateStack[d_stackIdx] = 
                    StatePair{ d_state = state, std::move(d_val_) };

    d_vsp = &d_stateStack[d_stackIdx];

    if (d_stackIdx == 0)
    {
    // $insert debug
    if (d_debug_)
        s_out_ <<   "\nPUSH 0 (initializing the state stack)" << '\n' << dflush_;
    }
    else
    {
    // $insert debug
    if (d_debug_)
        s_out_ <<   "\nPUSH:   [" << (d_vsp - 1)->first << ", " << symbol_(d_token) << "] -> " << state << stype_(" (semantic TOS = ", d_val_, ")") << '\n' << dflush_;
    }
}

// base/pushtoken
void URITokenizerBase::pushToken_(int token)
{
    d_next = TokenPair{ d_token, std::move(d_val_) };
    d_token = token;
}

// base/redotoken
void URITokenizerBase::redoToken_()
{
    if (d_token != Reserved_::UNDETERMINED_)
        pushToken_(d_token);
}

// base/reduce
void URITokenizerBase::reduce_(int rule)
{
    PI_ const &pi = s_productionInfo[rule];

    d_token = pi.d_nonTerm;
    // $insert debug
    if (d_debug_)
        s_out_ <<  "rule " << (&pi - s_productionInfo) << ": pop " << pi.d_size << " elements. Next will be: [" << d_stateStack[d_stackIdx - pi.d_size].first << ", " << symbol_(d_token) << ']' << '\n' << dflush_;
    pop_(pi.d_size);

    d_terminalToken = false;
}

// base/shift
void URITokenizerBase::shift_(int action)
{
    push_(action);
    popToken_();               // token processed

    if (d_recovery and d_terminalToken)
    {
        // $insert debug
        if (d_debug_)
            s_out_ <<  "ERROR RECOVERED: next state " << action << '\n' << dflush_;
        d_recovery = false;
        d_acceptedTokens_ = 0;
    }
}

// base/startrecovery
void URITokenizerBase::startRecovery_()
{
    int lastToken = d_token;                // give the unexpected token a
                                            // chance to be processed
                                            // again.

    pushToken_(Reserved_::errTok_);      // specify errTok_ as next token
    push_(lookup_());                     // push the error state

    d_token = lastToken;                    // reactivate the unexpected
                                            // token (we're now in an
                                            // ERROR state).

    d_recovery = true;
}

// base/top
inline size_t URITokenizerBase::top_() const
{
    return d_stateStack[d_stackIdx].first;
}

// derived/errorrecovery
void URITokenizer::errorRecovery_()
{
    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)

    // $insert debug
    if (d_debug_)
        s_out_ <<  "\nERROR:  [" << top_() << ", " << symbol_(token_()) << "] -> ??. Errors: " << (d_nErrors_ + 1) << '\n' << dflush_;


    if (d_acceptedTokens_ >= d_requiredTokens_)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors_;                          // were accepted. Otherwise
        error();                                // simply skip input
    }

    // get the error state
    while (not (s_state[top_()][0].d_type & ERR_ITEM))
    {
        // $insert debug
        if (d_debug_)
            s_out_ <<  "pop state: " << top_() << " (not an ERROR state)" << '\n' << dflush_;
        pop_();
    }
    // $insert debug
    if (d_debug_)
        s_out_ <<  "Reached ERROR state " << top_() << '\n' << dflush_;

    // In the error state, looking up a token allows us to proceed.
    // Continuation may be require multiple reductions, but eventually a
    // terminal-token shift is used. See nextCycle_ for details.

    startRecovery_();
}

// derived/executeaction
void URITokenizer::executeAction_(int production)
try
{
    if (token_() != Reserved_::UNDETERMINED_)
        pushToken_(token_());     // save an already available token
    // $insert debug
    if (d_debug_)
        s_out_ <<  "execute action " << production << " ..." << '\n' << dflush_;
// $insert executeactioncases

    if (d_actionCases_)
        s_out_ << "executeAction case " << production << '\n' << dflush_;
    switch (production)
    {
        // $insert actioncases
        
        case 1:
        {
         std::cout << d_scanner.matched() << std::endl << std::flush;
         }
        break;

        case 2:
        {
         std::cout << d_scanner.matched() << std::endl << std::flush;
         }
        break;

        case 3:
        {
         std::cout << d_scanner.matched() << std::endl << std::flush;
         }
        break;

        case 5:
        {
            d_val_ = vs_(-2);
        }
        break;

        case 7:
        {
            d_val_ = vs_(-2);
        }
        break;

        case 9:
        {
            d_val_ = vs_(-1);
        }
        break;

        case 10:
        {
            d_val_ = vs_(-2);
        }
        break;

        case 11:
        {
            d_val_ = vs_(-4);
        }
        break;

        case 13:
        {
            d_val_ = vs_(0);
        }
        break;

    }
    // $insert debug
    if (d_debug_)
        s_out_ <<  "... completed" << stype_(", semantic: ", vs_(0)) << '\n' << dflush_;
}
catch (std::exception const &exc)
{
    exceptionHandler(exc);
}

// derived/nextcycle
void URITokenizer::nextCycle_()
try
{
    if (s_state[state_()]->d_type & REQ_TOKEN)
        nextToken_();              // obtain next token


    int action = lookup_();        // lookup d_token in d_state

    if (action > 0)                 // SHIFT: push a new state
    {
        shift_(action);
        return;
    }

    if (action < 0)            // REDUCE: execute and pop.
    {
        // $insert debug
        if (d_debug_)
            s_out_ <<  "\nREDUCE: rule " << -action << '\n' << dflush_;

        if (recovery_())
            redoToken_();
        else
            executeAction_(-action);
                                            // next token is the rule's LHS
        reduce_(-action); 
        return;
    }

    if (recovery_())
        ABORT();
    else 
        ACCEPT();
}
catch (ErrorRecovery_)
{
    if (not recovery_())
        errorRecovery_();
    else
    {
        if (token_() == Reserved_::EOF_)
            ABORT();
        popToken_();               // skip the failing token
    }
}


// derived/nexttoken
void URITokenizer::nextToken_()
{ 
    // If d_token is Reserved_::UNDETERMINED_ then if savedToken_() is
    // Reserved_::UNDETERMINED_ another token is obtained from lex(). Then
    // savedToken_() is assigned to d_token.

                                    // no need for a token: got one already
    if (token_() != Reserved_::UNDETERMINED_) 
    {
        // $insert debug
        if (d_debug_)
            s_out_ <<  "available token " << symbol_(token_()) << '\n' << dflush_;
        return;                             
    }

    if (savedToken_() != Reserved_::UNDETERMINED_)
    {
        popToken_();               // consume pending token
        // $insert debug
        if (d_debug_)
            s_out_ <<  "retrieved token " << symbol_(token_()) << stype_(", semantic = ", d_val_) << '\n' << dflush_;
    }
    else
    {
        ++d_acceptedTokens_;       // accept another token (see
                                    // errorRecover())
        lex_(lex());
        print_();
        // $insert debug
        if (d_debug_)
            s_out_ <<  "scanner token " << symbol_(token_()) << '\n' << dflush_;
    }
    print();
}

// derived/print
void URITokenizer::print_()
{
// $insert print
}

// derived/parse
int URITokenizer::parse()
try 
{
    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and all relevant variables
    // are initialized by Base::clearin_.
    //
    // Then, in an eternal loop:
    //
    //  1. If a state is a REQ_TOKEN type, then the next token is obtained
    //     from nextToken().  This may very well be the currently available
    //     token. When retrieving a terminal token d_terminal is set to true.
    //
    //  2. lookup() is called, d_token is looked up in the current state's
    //     SR_ array.
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token is not found, and the state has no
    //     default reduction.

    // $insert debug
    if (d_debug_)
        s_out_ <<  "parse(): Parsing starts" << '\n' << dflush_;
    clearin_();                            // initialize, push(0)

    while (true)
    {
// $insert prompt

        if (d_debug_)
            s_out_ << '\n';

        nextCycle_();
    }
}
catch (Return_ retValue)
{
    // $insert debug
    if (d_debug_)
        s_out_ <<  "parse(): returns " << retValue << " or " << d_nErrors_  << '\n' << dflush_;
    return retValue or d_nErrors_;
}


// derived/tail

// $insert namespace-close
}

