#!/bin/bash

distro=$(lsb_release -sc)
fullbranch=$(git rev-parse --abbrev-ref HEAD)
environment=${fullbranch##*/}
remote=$(git remote)

if [[ -z $1 ]]
then
    current_ac=$(cat configure.ac | grep -F 'AC_INIT' | awk '{print $2}')
    current_ac=${current_ac%,}
    git tag -a "v$current_ac" -m "Version $current_ac"
    if [[ "$remote" != "" ]]
    then
        git push origin "v$current_ac"
    fi

    dch -m -U -D $distro "Version bump"
    new_ac=$(head -n 1 debian/changelog | awk '{print $2}')
    new_ac=${new_ac%)}
    new_ac=${new_ac##(}
			       
    if [[ $current_ac != "" ]]
    then
	sed -i "s/, $current_ac,/, $new_ac,/g" configure.ac
    fi
else
    current_ac=$(cat configure.ac | grep -F 'AC_INIT' | awk '{print $2}')
    current_ac=${current_ac%,}
    git tag -a "v$current_ac" -m "Version $current_ac"
    if [[ "$remote" != "" ]]
    then
        git push origin "v$current_ac"
    fi

    if [[ "$environment" == "master" ]]
    then
	dch -v "$1.$2.$3-1${distro}1" -m -U -D ${distro} "Version bump"
    else
	dch -v "$1.$2.$3-1${distro}+${environment}1" -m -U -D ${distro} "Version bump"
    fi
    
    if [[ $current_ac != "" ]]
    then
	if [[ "$environment" == "master" ]]
	then
	    sed -i "s/, $current_ac,/, $1.$2.$3-1${distro}1,/g" configure.ac
	else
	    sed -i "s/, $current_ac,/, $1.$2.$3-1${distro}+${environment}1,/g" configure.ac
	fi
    fi

    major=$(($1 + $2))

    zinit --version $1 $2 $3
    
    current_lib=$(find . -name 'Makefile.am' -print -quit | xargs -L 1 grep -m 1 -F 'version-info' | awk '{print $4}')
    if [[ $current_lib != "" ]]
    then
	find . -name "Makefile.am" | xargs -L 1 grep -l -F 'version-info' | xargs -L 1 sed -i "s/-version-info $current_lib/-version-info $major:$3:$2/g"
    fi
fi
