// Generated by Flexc++ V2.07.07 on Sat, 16 May 2020 17:00:01 -44156800

// $insert class_h
#include <zapata/http/HTTPLexer.h>
#include <string.h>
#include <zapata/text/convert.h>
#include <zapata/http/HTTPObj.h>
#include <sstream>

// $insert namespace-use
// UN-comment the next using-declaration if you want to use
// symbols from the namespace zpt without prefixing zpt::
// using namespace zpt;
