// Generated by Flexc++ V2.15.00 on Mon, 21 Apr 2025 23:15:08 +0100

// $insert class_h
#include <zapata/http/HTTPLexer.h>
#include <string.h>
#include <zapata/text/convert.h>
#include <zapata/http/HTTPObj.h>
#include <sstream>

// $insert namespace-use
// UN-comment the next using-declaration if you want to use
// symbols from the namespace zpt without prefixing zpt::
// using namespace zpt;
