// Generated by Bisonc++ V6.02.05 on Sat, 25 Apr 2020 17:26:19 +0100

// Include this file in the sources of the class HTTPTokenizer.

// $insert class.h
#include <zapata/http/HTTPTokenizer.h>

// $insert namespace-open
namespace zpt {

inline void
HTTPTokenizer::error() {
    throw zpt::SyntaxErrorException(std::string("Syntax error in line ") +
                                    std::to_string(d_scanner.lineNr()));
}

// $insert lex
inline int
HTTPTokenizer::lex() {
    return d_scanner.lex();
}

inline void
HTTPTokenizer::print() {}

inline void
HTTPTokenizer::exceptionHandler(std::exception const& exc) {
    throw; // re-implement to handle exceptions thrown by actions
}

// $insert namespace-close
}

// Add here includes that are only required for the compilation
// of HTTPTokenizer's sources.

// $insert namespace-use
// UN-comment the next using-declaration if you want to use
// symbols from the namespace zpt without specifying zpt::
// using namespace zpt;

// UN-comment the next using-declaration if you want to use
// int HTTPTokenizer's sources symbols from the namespace std without
// specifying std::

// using namespace std;
