// Generated by Flexc++ V2.11.00 on Sun, 31 Jul 2022 15:46:39 +0100

// $insert class_h
#include <zapata/http/HTTPLexer.h>
#include <string.h>
#include <zapata/text/convert.h>
#include <zapata/http/HTTPObj.h>
#include <sstream>

// $insert namespace-use
// UN-comment the next using-declaration if you want to use
// symbols from the namespace zpt without prefixing zpt::
// using namespace zpt;
