name: C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v1
    - name: Update OS
      run: sudo apt update
    - name: Install dependencies I
      run: sudo apt -y install libsystemd-dev libcrypto++-dev libssl-dev libssl1.1 libmagic-dev libossp-uuid-dev g++ cmake libsqlite3-dev python3 libpython3-dev lua5.2 liblua5.2-dev
    - name: Configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=release -DCMAKE_INSTALL_PREFIX=/usr/local/zapata
    - name: Build
      run: cmake --build build
